spring.application.name=demoSpring
spring.datasource.driver-class-name=org.postgresql.Driver
# jdbc_db
spring.datasource.url=jdbc:postgresql://localhost:5432/jdbc_db    
# postgres
spring.datasource.username=postgres     
# hayal026jp
spring.datasource.password=hayal026jp