spring.application.name=task_p
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db
spring.datasource.username=appuser
spring.datasource.password=AppPass123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update